/// https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
///
/// From https://github.com/meikidd/iso-639-1
///


/**
 * Works with (all?) parts of ISO 639.
 */
export const wikiLink = (code: string) => {
	return `https://en.wikipedia.org/wiki/ISO_639:${code}`;
}


export const MAPPING_ISO_639_1 = {
	aa: {
		name: 'Afar',
		nativeName: 'Afaraf',
	},
	ab: {
		name: 'Abkhaz',
		nativeName: 'аҧсуа бызшәа',
	},
	ae: {
		name: 'Avestan',
		nativeName: 'avesta',
	},
	af: {
		name: 'Afrikaans',
		nativeName: 'Afrikaans',
	},
	ak: {
		name: 'Akan',
		nativeName: 'Akan',
	},
	am: {
		name: 'Amharic',
		nativeName: 'አማርኛ',
	},
	an: {
		name: 'Aragonese',
		nativeName: 'aragonés',
	},
	ar: {
		name: 'Arabic',
		nativeName: 'اللغة العربية',
	},
	as: {
		name: 'Assamese',
		nativeName: 'অসমীয়া',
	},
	av: {
		name: 'Avaric',
		nativeName: 'авар мацӀ',
	},
	ay: {
		name: 'Aymara',
		nativeName: 'aymar aru',
	},
	az: {
		name: 'Azerbaijani',
		nativeName: 'azərbaycan dili',
	},
	ba: {
		name: 'Bashkir',
		nativeName: 'башҡорт теле',
	},
	be: {
		name: 'Belarusian',
		nativeName: 'беларуская мова',
	},
	bg: {
		name: 'Bulgarian',
		nativeName: 'български език',
	},
	bh: {
		name: 'Bihari',
		nativeName: 'भोजपुरी',
	},
	bi: {
		name: 'Bislama',
		nativeName: 'Bislama',
	},
	bm: {
		name: 'Bambara',
		nativeName: 'bamanankan',
	},
	bn: {
		name: 'Bengali',
		nativeName: 'বাংলা',
	},
	bo: {
		name: 'Tibetan Standard',
		nativeName: 'བོད་ཡིག',
	},
	br: {
		name: 'Breton',
		nativeName: 'brezhoneg',
	},
	bs: {
		name: 'Bosnian',
		nativeName: 'bosanski jezik',
	},
	ca: {
		name: 'Catalan',
		nativeName: 'Català',
	},
	ce: {
		name: 'Chechen',
		nativeName: 'нохчийн мотт',
	},
	ch: {
		name: 'Chamorro',
		nativeName: 'Chamoru',
	},
	co: {
		name: 'Corsican',
		nativeName: 'corsu',
	},
	cr: {
		name: 'Cree',
		nativeName: 'ᓀᐦᐃᔭᐍᐏᐣ',
	},
	cs: {
		name: 'Czech',
		nativeName: 'čeština',
	},
	cu: {
		name: 'Old Church Slavonic',
		nativeName: 'ѩзыкъ словѣньскъ',
	},
	cv: {
		name: 'Chuvash',
		nativeName: 'чӑваш чӗлхи',
	},
	cy: {
		name: 'Welsh',
		nativeName: 'Cymraeg',
	},
	da: {
		name: 'Danish',
		nativeName: 'dansk',
	},
	de: {
		name: 'German',
		nativeName: 'Deutsch',
	},
	dv: {
		name: 'Divehi',
		nativeName: 'Dhivehi',
	},
	dz: {
		name: 'Dzongkha',
		nativeName: 'རྫོང་ཁ',
	},
	ee: {
		name: 'Ewe',
		nativeName: 'Eʋegbe',
	},
	el: {
		name: 'Greek',
		nativeName: 'Ελληνικά',
	},
	en: {
		name: 'English',
		nativeName: 'English',
	},
	eo: {
		name: 'Esperanto',
		nativeName: 'Esperanto',
	},
	es: {
		name: 'Spanish',
		nativeName: 'Español',
	},
	et: {
		name: 'Estonian',
		nativeName: 'eesti',
	},
	eu: {
		name: 'Basque',
		nativeName: 'euskara',
	},
	fa: {
		name: 'Persian',
		nativeName: 'فارسی',
	},
	ff: {
		name: 'Fula',
		nativeName: 'Fulfulde',
	},
	fi: {
		name: 'Finnish',
		nativeName: 'suomi',
	},
	fj: {
		name: 'Fijian',
		nativeName: 'Vakaviti',
	},
	fo: {
		name: 'Faroese',
		nativeName: 'føroyskt',
	},
	fr: {
		name: 'French',
		nativeName: 'Français',
	},
	fy: {
		name: 'Western Frisian',
		nativeName: 'Frysk',
	},
	ga: {
		name: 'Irish',
		nativeName: 'Gaeilge',
	},
	gd: {
		name: 'Scottish Gaelic',
		nativeName: 'Gàidhlig',
	},
	gl: {
		name: 'Galician',
		nativeName: 'galego',
	},
	gn: {
		name: 'Guaraní',
		nativeName: "Avañe'ẽ",
	},
	gu: {
		name: 'Gujarati',
		nativeName: 'ગુજરાતી',
	},
	gv: {
		name: 'Manx',
		nativeName: 'Gaelg',
	},
	ha: {
		name: 'Hausa',
		nativeName: 'هَوُسَ',
	},
	he: {
		name: 'Hebrew',
		nativeName: 'עברית',
	},
	hi: {
		name: 'Hindi',
		nativeName: 'हिन्दी',
	},
	ho: {
		name: 'Hiri Motu',
		nativeName: 'Hiri Motu',
	},
	hr: {
		name: 'Croatian',
		nativeName: 'hrvatski jezik',
	},
	ht: {
		name: 'Haitian',
		nativeName: 'Kreyòl ayisyen',
	},
	hu: {
		name: 'Hungarian',
		nativeName: 'magyar',
	},
	hy: {
		name: 'Armenian',
		nativeName: 'Հայերեն',
	},
	hz: {
		name: 'Herero',
		nativeName: 'Otjiherero',
	},
	ia: {
		name: 'Interlingua',
		nativeName: 'Interlingua',
	},
	id: {
		name: 'Indonesian',
		nativeName: 'Bahasa Indonesia',
	},
	ie: {
		name: 'Interlingue',
		nativeName: 'Interlingue',
	},
	ig: {
		name: 'Igbo',
		nativeName: 'Asụsụ Igbo',
	},
	ii: {
		name: 'Nuosu',
		nativeName: 'ꆈꌠ꒿ Nuosuhxop',
	},
	ik: {
		name: 'Inupiaq',
		nativeName: 'Iñupiaq',
	},
	io: {
		name: 'Ido',
		nativeName: 'Ido',
	},
	is: {
		name: 'Icelandic',
		nativeName: 'Íslenska',
	},
	it: {
		name: 'Italian',
		nativeName: 'Italiano',
	},
	iu: {
		name: 'Inuktitut',
		nativeName: 'ᐃᓄᒃᑎᑐᑦ',
	},
	ja: {
		name: 'Japanese',
		nativeName: '日本語',
	},
	jv: {
		name: 'Javanese',
		nativeName: 'basa Jawa',
	},
	ka: {
		name: 'Georgian',
		nativeName: 'ქართული',
	},
	kg: {
		name: 'Kongo',
		nativeName: 'Kikongo',
	},
	ki: {
		name: 'Kikuyu',
		nativeName: 'Gĩkũyũ',
	},
	kj: {
		name: 'Kwanyama',
		nativeName: 'Kuanyama',
	},
	kk: {
		name: 'Kazakh',
		nativeName: 'қазақ тілі',
	},
	kl: {
		name: 'Kalaallisut',
		nativeName: 'kalaallisut',
	},
	km: {
		name: 'Khmer',
		nativeName: 'ខេមរភាសា',
	},
	kn: {
		name: 'Kannada',
		nativeName: 'ಕನ್ನಡ',
	},
	ko: {
		name: 'Korean',
		nativeName: '한국어',
	},
	kr: {
		name: 'Kanuri',
		nativeName: 'Kanuri',
	},
	ks: {
		name: 'Kashmiri',
		nativeName: 'कश्मीरी',
	},
	ku: {
		name: 'Kurdish',
		nativeName: 'Kurdî',
	},
	kv: {
		name: 'Komi',
		nativeName: 'коми кыв',
	},
	kw: {
		name: 'Cornish',
		nativeName: 'Kernewek',
	},
	ky: {
		name: 'Kyrgyz',
		nativeName: 'Кыргызча',
	},
	la: {
		name: 'Latin',
		nativeName: 'latine',
	},
	lb: {
		name: 'Luxembourgish',
		nativeName: 'Lëtzebuergesch',
	},
	lg: {
		name: 'Ganda',
		nativeName: 'Luganda',
	},
	li: {
		name: 'Limburgish',
		nativeName: 'Limburgs',
	},
	ln: {
		name: 'Lingala',
		nativeName: 'Lingála',
	},
	lo: {
		name: 'Lao',
		nativeName: 'ພາສາ',
	},
	lt: {
		name: 'Lithuanian',
		nativeName: 'lietuvių kalba',
	},
	lu: {
		name: 'Luba-Katanga',
		nativeName: 'Tshiluba',
	},
	lv: {
		name: 'Latvian',
		nativeName: 'latviešu valoda',
	},
	mg: {
		name: 'Malagasy',
		nativeName: 'fiteny malagasy',
	},
	mh: {
		name: 'Marshallese',
		nativeName: 'Kajin M̧ajeļ',
	},
	mi: {
		name: 'Māori',
		nativeName: 'te reo Māori',
	},
	mk: {
		name: 'Macedonian',
		nativeName: 'македонски јазик',
	},
	ml: {
		name: 'Malayalam',
		nativeName: 'മലയാളം',
	},
	mn: {
		name: 'Mongolian',
		nativeName: 'Монгол хэл',
	},
	mr: {
		name: 'Marathi',
		nativeName: 'मराठी',
	},
	ms: {
		name: 'Malay',
		nativeName: 'Bahasa Malaysia',
	},
	mt: {
		name: 'Maltese',
		nativeName: 'Malti',
	},
	my: {
		name: 'Burmese',
		nativeName: 'ဗမာစာ',
	},
	na: {
		name: 'Nauru',
		nativeName: 'Ekakairũ Naoero',
	},
	nb: {
		name: 'Norwegian Bokmål',
		nativeName: 'Norsk bokmål',
	},
	nd: {
		name: 'Northern Ndebele',
		nativeName: 'isiNdebele',
	},
	ne: {
		name: 'Nepali',
		nativeName: 'नेपाली',
	},
	ng: {
		name: 'Ndonga',
		nativeName: 'Owambo',
	},
	nl: {
		name: 'Dutch',
		nativeName: 'Nederlands',
	},
	nn: {
		name: 'Norwegian Nynorsk',
		nativeName: 'Norsk nynorsk',
	},
	no: {
		name: 'Norwegian',
		nativeName: 'Norsk',
	},
	nr: {
		name: 'Southern Ndebele',
		nativeName: 'isiNdebele',
	},
	nv: {
		name: 'Navajo',
		nativeName: 'Diné bizaad',
	},
	ny: {
		name: 'Chichewa',
		nativeName: 'chiCheŵa',
	},
	oc: {
		name: 'Occitan',
		nativeName: 'occitan',
	},
	oj: {
		name: 'Ojibwe',
		nativeName: 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
	},
	om: {
		name: 'Oromo',
		nativeName: 'Afaan Oromoo',
	},
	or: {
		name: 'Oriya',
		nativeName: 'ଓଡ଼ିଆ',
	},
	os: {
		name: 'Ossetian',
		nativeName: 'ирон æвзаг',
	},
	pa: {
		name: 'Panjabi',
		nativeName: 'ਪੰਜਾਬੀ',
	},
	pi: {
		name: 'Pāli',
		nativeName: 'पाऴि',
	},
	pl: {
		name: 'Polish',
		nativeName: 'język polski',
	},
	ps: {
		name: 'Pashto',
		nativeName: 'پښتو',
	},
	pt: {
		name: 'Portuguese',
		nativeName: 'Português',
	},
	qu: {
		name: 'Quechua',
		nativeName: 'Runa Simi',
	},
	rm: {
		name: 'Romansh',
		nativeName: 'rumantsch grischun',
	},
	rn: {
		name: 'Kirundi',
		nativeName: 'Ikirundi',
	},
	ro: {
		name: 'Romanian',
		nativeName: 'Română',
	},
	ru: {
		name: 'Russian',
		nativeName: 'Русский',
	},
	rw: {
		name: 'Kinyarwanda',
		nativeName: 'Ikinyarwanda',
	},
	sa: {
		name: 'Sanskrit',
		nativeName: 'संस्कृतम्',
	},
	sc: {
		name: 'Sardinian',
		nativeName: 'sardu',
	},
	sd: {
		name: 'Sindhi',
		nativeName: 'सिन्धी',
	},
	se: {
		name: 'Northern Sami',
		nativeName: 'Davvisámegiella',
	},
	sg: {
		name: 'Sango',
		nativeName: 'yângâ tî sängö',
	},
	si: {
		name: 'Sinhala',
		nativeName: 'සිංහල',
	},
	sk: {
		name: 'Slovak',
		nativeName: 'slovenčina',
	},
	sl: {
		name: 'Slovene',
		nativeName: 'slovenski jezik',
	},
	sm: {
		name: 'Samoan',
		nativeName: "gagana fa'a Samoa",
	},
	sn: {
		name: 'Shona',
		nativeName: 'chiShona',
	},
	so: {
		name: 'Somali',
		nativeName: 'Soomaaliga',
	},
	sq: {
		name: 'Albanian',
		nativeName: 'Shqip',
	},
	sr: {
		name: 'Serbian',
		nativeName: 'српски језик',
	},
	ss: {
		name: 'Swati',
		nativeName: 'SiSwati',
	},
	st: {
		name: 'Southern Sotho',
		nativeName: 'Sesotho',
	},
	su: {
		name: 'Sundanese',
		nativeName: 'Basa Sunda',
	},
	sv: {
		name: 'Swedish',
		nativeName: 'svenska',
	},
	sw: {
		name: 'Swahili',
		nativeName: 'Kiswahili',
	},
	ta: {
		name: 'Tamil',
		nativeName: 'தமிழ்',
	},
	te: {
		name: 'Telugu',
		nativeName: 'తెలుగు',
	},
	tg: {
		name: 'Tajik',
		nativeName: 'тоҷикӣ',
	},
	th: {
		name: 'Thai',
		nativeName: 'ไทย',
	},
	ti: {
		name: 'Tigrinya',
		nativeName: 'ትግርኛ',
	},
	tk: {
		name: 'Turkmen',
		nativeName: 'Türkmen',
	},
	tl: {
		name: 'Tagalog',
		nativeName: 'Wikang Tagalog',
	},
	tn: {
		name: 'Tswana',
		nativeName: 'Setswana',
	},
	to: {
		name: 'Tonga',
		nativeName: 'faka Tonga',
	},
	tr: {
		name: 'Turkish',
		nativeName: 'Türkçe',
	},
	ts: {
		name: 'Tsonga',
		nativeName: 'Xitsonga',
	},
	tt: {
		name: 'Tatar',
		nativeName: 'татар теле',
	},
	tw: {
		name: 'Twi',
		nativeName: 'Twi',
	},
	ty: {
		name: 'Tahitian',
		nativeName: 'Reo Tahiti',
	},
	ug: {
		name: 'Uyghur',
		nativeName: 'ئۇيغۇرچە‎',
	},
	uk: {
		name: 'Ukrainian',
		nativeName: 'Українська',
	},
	ur: {
		name: 'Urdu',
		nativeName: 'اردو',
	},
	uz: {
		name: 'Uzbek',
		nativeName: 'Ўзбек',
	},
	ve: {
		name: 'Venda',
		nativeName: 'Tshivenḓa',
	},
	vi: {
		name: 'Vietnamese',
		nativeName: 'Tiếng Việt',
	},
	vo: {
		name: 'Volapük',
		nativeName: 'Volapük',
	},
	wa: {
		name: 'Walloon',
		nativeName: 'walon',
	},
	wo: {
		name: 'Wolof',
		nativeName: 'Wollof',
	},
	xh: {
		name: 'Xhosa',
		nativeName: 'isiXhosa',
	},
	yi: {
		name: 'Yiddish',
		nativeName: 'ייִדיש',
	},
	yo: {
		name: 'Yoruba',
		nativeName: 'Yorùbá',
	},
	za: {
		name: 'Zhuang',
		nativeName: 'Saɯ cueŋƅ',
	},
	zh: {
		name: 'Chinese',
		nativeName: '中文',
	},
	zu: {
		name: 'Zulu',
		nativeName: 'isiZulu',
	},
};


/// https://en.wikipedia.org/wiki/ISO_639-2
/// In general the T codes are favored; ISO 639-3 uses ISO 639-2/T.
///
/// https://github.com/fabulator/iso-639-2-english
///

const MAPPING_ISO_639_2: Record<string, Record<string, string>> = {
	ancient: {
		akk: 'Akkadian',
		arc: 'Official Aramaic',
		ave: 'Avestan',
		chu: 'Church Slavic',
		egy: 'Egyptian',
		elx: 'Elamite',
		gez: 'Geez',
		got: 'Gothic',
		hit: 'Hittite',
		kaw: 'Kawi',
		kho: 'Khotanese',
		lat: 'Latin',
		pal: 'Pahlavi',
		phn: 'Phoenician',
		pli: 'Pali',
		san: 'Sanskrit',
		sog: 'Sogdian',
		sux: 'Sumerian',
		uga: 'Ugaritic'
	},
	constructed: {
		afh: 'Afrihili',
		epo: 'Esperanto',
		ido: 'Ido',
		ile: 'Interlingue',
		ina: 'Interlingua',
		jbo: 'Lojban',
		tlh: 'Klingon',
		vol: 'Volapük',
		zbl: 'Blissymbols'
	},
	extinct: {
		chb: 'Chibcha',
		chg: 'Chagatai',
		cop: 'Coptic',
		sam: 'Samaritan Aramaic'
	},
	historical: {
		ang: 'Old English',
		dum: 'Middle Dutch',
		enm: 'Middle English',
		frm: 'Middle French',
		fro: 'Old French',
		gmh: 'Middle High German',
		goh: 'Old High German',
		grc: 'Ancient Greek',
		mga: 'Middle Irish',
		non: 'Old Norse',
		nwc: 'Classical Newari',
		ota: 'Ottoman Turkish',
		peo: 'Old Persian',
		pro: 'Old Provençal',
		sga: 'Old Irish',
		syc: 'Classical Syriac'
	},
	living: {
		aar: 'Afar',
		abk: 'Abkhazian',
		ace: 'Achinese',
		ach: 'Acoli',
		ada: 'Adangme',
		ady: 'Adyghe',
		afr: 'Afrikaans',
		ain: 'Ainu',
		aka: 'Akan',
		alb: 'Albanian',
		sqi: 'Albanian',
		ale: 'Aleut',
		alt: 'Southern Altai',
		amh: 'Amharic',
		anp: 'Angika',
		ara: 'Arabic',
		arg: 'Aragonese',
		arm: 'Armenian',
		hye: 'Armenian',
		arn: 'Mapudungun',
		arp: 'Arapaho',
		arw: 'Arawak',
		asm: 'Assamese',
		ast: 'Asturian',
		ava: 'Avaric',
		awa: 'Awadhi',
		aym: 'Aymara',
		aze: 'Azerbaijani',
		bak: 'Bashkir',
		bal: 'Baluchi',
		bam: 'Bambara',
		ban: 'Balinese',
		baq: 'Basque',
		eus: 'Basque',
		bas: 'Basa',
		bej: 'Beja',
		bel: 'Belarusian',
		bem: 'Bemba',
		ben: 'Bengali',
		bho: 'Bhojpuri',
		bik: 'Bikol',
		bin: 'Bini',
		bis: 'Bislama',
		bla: 'Siksika',
		bod: 'Tibetan',
		tib: 'Tibetan',
		bos: 'Bosnian',
		bra: 'Braj',
		bre: 'Breton',
		bua: 'Buriat',
		bug: 'Buginese',
		bul: 'Bulgarian',
		bur: 'Burmese',
		mya: 'Burmese',
		byn: 'Bilin',
		cad: 'Caddo',
		car: 'Galibi Carib',
		cat: 'Catalan',
		ceb: 'Cebuano',
		ces: 'Czech',
		cze: 'Czech',
		cha: 'Chamorro',
		che: 'Chechen',
		chi: 'Chinese',
		zho: 'Chinese',
		chk: 'Chuukese',
		chm: 'Mari',
		chn: 'Chinook jargon',
		cho: 'Choctaw',
		chp: 'Chipewyan',
		chr: 'Cherokee',
		chv: 'Chuvash',
		chy: 'Cheyenne',
		cor: 'Cornish',
		cos: 'Corsican',
		cre: 'Cree',
		crh: 'Crimean Tatar',
		csb: 'Kashubian',
		cym: 'Welsh',
		wel: 'Welsh',
		dak: 'Dakota',
		dan: 'Danish',
		dar: 'Dargwa',
		del: 'Delaware',
		den: 'Slave',
		deu: 'German',
		ger: 'German',
		dgr: 'Dogrib',
		din: 'Dinka',
		div: 'Dhivehi',
		doi: 'Dogri',
		dsb: 'Lower Sorbian',
		dua: 'Duala',
		dut: 'Dutch',
		nld: 'Dutch',
		dyu: 'Dyula',
		dzo: 'Dzongkha',
		efi: 'Efik',
		eka: 'Ekajuk',
		ell: 'Modern Greek',
		gre: 'Modern Greek',
		eng: 'English',
		est: 'Estonian',
		ewe: 'Ewe',
		ewo: 'Ewondo',
		fan: 'Fang',
		fao: 'Faroese',
		fas: 'Persian',
		per: 'Persian',
		fat: 'Fanti',
		fij: 'Fijian',
		fil: 'Filipino',
		fin: 'Finnish',
		fon: 'Fon',
		fra: 'French',
		fre: 'French',
		frr: 'Northern Frisian',
		frs: 'Eastern Frisian',
		fry: 'Western Frisian',
		ful: 'Fulah',
		fur: 'Friulian',
		gaa: 'Ga',
		gay: 'Gayo',
		gba: 'Gbaya',
		geo: 'Georgian',
		kat: 'Georgian',
		gil: 'Gilbertese',
		gla: 'Gaelic',
		gle: 'Irish',
		glg: 'Galician',
		glv: 'Manx',
		gon: 'Gondi',
		gor: 'Gorontalo',
		grb: 'Grebo',
		grn: 'Guarani',
		gsw: 'Swiss German',
		guj: 'Gujarati',
		gwi: 'Gwichʼin',
		hai: 'Haida',
		hat: 'Haitian',
		hau: 'Hausa',
		haw: 'Hawaiian',
		heb: 'Hebrew',
		her: 'Herero',
		hil: 'Hiligaynon',
		hin: 'Hindi',
		hmn: 'Hmong',
		hmo: 'Hiri Motu',
		hrv: 'Croatian',
		hsb: 'Upper Sorbian',
		hun: 'Hungarian',
		hup: 'Hupa',
		iba: 'Iban',
		ibo: 'Igbo',
		ice: 'Icelandic',
		isl: 'Icelandic',
		iii: 'Sichuan Yi',
		iku: 'Inuktitut',
		ilo: 'Iloko',
		ind: 'Indonesian',
		inh: 'Ingush',
		ipk: 'Inupiaq',
		ita: 'Italian',
		jav: 'Javanese',
		jpn: 'Japanese',
		jpr: 'Judeo-Persian',
		jrb: 'Judeo-Arabic',
		kaa: 'Kara-Kalpak',
		kab: 'Kabyle',
		kac: 'Kachin',
		kal: 'Kalaallisut',
		kam: 'Kamba',
		kan: 'Kannada',
		kas: 'Kashmiri',
		kau: 'Kanuri',
		kaz: 'Kazakh',
		kbd: 'Kabardian',
		kha: 'Khasi',
		khm: 'Central Khmer',
		kik: 'Kikuyu',
		kin: 'Kinyarwanda',
		kir: 'Kirghiz',
		kmb: 'Kimbundu',
		kok: 'Konkani',
		kom: 'Komi',
		kon: 'Kongo',
		kor: 'Korean',
		kos: 'Kosraean',
		kpe: 'Kpelle',
		krc: 'Karachay-Balkar',
		krl: 'Karelian',
		kru: 'Kurukh',
		kua: 'Kuanyama',
		kum: 'Kumyk',
		kur: 'Kurdish',
		kut: 'Kutenai',
		lad: 'Ladino',
		lah: 'Lahnda',
		lam: 'Lamba',
		lao: 'Lao',
		lav: 'Latvian',
		lez: 'Lezghian',
		lim: 'Limburgan',
		lin: 'Lingala',
		lit: 'Lithuanian',
		lol: 'Mongo',
		loz: 'Lozi',
		ltz: 'Luxembourgish',
		lua: 'Luba-Lulua',
		lub: 'Luba-Katanga',
		lug: 'Ganda',
		lui: 'Luiseno',
		lun: 'Lunda',
		luo: 'Luo',
		lus: 'Lushai',
		mac: 'Macedonian',
		mkd: 'Macedonian',
		mad: 'Madurese',
		mag: 'Magahi',
		mah: 'Marshallese',
		mai: 'Maithili',
		mak: 'Makasar',
		mal: 'Malayalam',
		man: 'Mandingo',
		mao: 'Maori',
		mri: 'Maori',
		mar: 'Marathi',
		mas: 'Masai',
		may: 'Malay',
		msa: 'Malay',
		mdf: 'Moksha',
		mdr: 'Mandar',
		men: 'Mende',
		mic: "Mi'kmaq",
		min: 'Minangkabau',
		mlg: 'Malagasy',
		mlt: 'Maltese',
		mnc: 'Manchu',
		mni: 'Manipuri',
		moh: 'Mohawk',
		mon: 'Mongolian',
		mos: 'Mossi',
		mus: 'Creek',
		mwl: 'Mirandese',
		mwr: 'Marwari',
		myv: 'Erzya',
		nap: 'Neapolitan',
		nau: 'Nauru',
		nav: 'Navajo',
		nbl: 'South Ndebele',
		nde: 'North Ndebele',
		ndo: 'Ndonga',
		nds: 'Low German',
		nep: 'Nepali',
		new: 'Nepal Bhasa',
		nia: 'Nias',
		niu: 'Niuean',
		nno: 'Norwegian Nynorsk',
		nob: 'Norwegian Bokmål',
		nog: 'Nogai',
		nor: 'Norwegian',
		nqo: "N'Ko",
		nso: 'Pedi',
		nya: 'Chichewa',
		nym: 'Nyamwezi',
		nyn: 'Nyankole',
		nyo: 'Nyoro',
		nzi: 'Nzima',
		oci: 'Occitan',
		oji: 'Ojibwa',
		ori: 'Oriya',
		orm: 'Oromo',
		osa: 'Osage',
		oss: 'Ossetian',
		pag: 'Pangasinan',
		pam: 'Pampanga',
		pan: 'Panjabi',
		pap: 'Papiamento',
		pau: 'Palauan',
		pol: 'Polish',
		pon: 'Pohnpeian',
		por: 'Portuguese',
		pus: 'Pushto',
		que: 'Quechua',
		raj: 'Rajasthani',
		rap: 'Rapanui',
		rar: 'Rarotongan',
		roh: 'Romansh',
		rom: 'Romany',
		ron: 'Romanian',
		rum: 'Romanian',
		run: 'Rundi',
		rup: 'Aromanian',
		rus: 'Russian',
		sad: 'Sandawe',
		sag: 'Sango',
		sah: 'Yakut',
		sas: 'Sasak',
		sat: 'Santali',
		scn: 'Sicilian',
		sco: 'Scots',
		sel: 'Selkup',
		shn: 'Shan',
		sid: 'Sidamo',
		sin: 'Sinhala',
		slo: 'Slovak',
		slk: 'Slovak',
		slv: 'Slovenian',
		sma: 'Southern Sami',
		sme: 'Northern Sami',
		smj: 'Lule Sami',
		smn: 'Inari Sami',
		smo: 'Samoan',
		sms: 'Skolt Sami',
		sna: 'Shona',
		snd: 'Sindhi',
		snk: 'Soninke',
		som: 'Somali',
		sot: 'Southern Sotho',
		spa: 'Spanish',
		srd: 'Sardinian',
		srn: 'Sranan Tongo',
		srp: 'Serbian',
		srr: 'Serer',
		ssw: 'Swati',
		suk: 'Sukuma',
		sun: 'Sundanese',
		sus: 'Susu',
		swa: 'Swahili',
		swe: 'Swedish',
		syr: 'Syriac',
		tah: 'Tahitian',
		tam: 'Tamil',
		tat: 'Tatar',
		tel: 'Telugu',
		tem: 'Timne',
		ter: 'Tereno',
		tet: 'Tetum',
		tgk: 'Tajik',
		tgl: 'Tagalog',
		tha: 'Thai',
		tig: 'Tigre',
		tir: 'Tigrinya',
		tiv: 'Tiv',
		tkl: 'Tokelau',
		tli: 'Tlingit',
		tmh: 'Tamashek',
		tog: 'Tonga',
		ton: 'Tonga',
		tpi: 'Tok Pisin',
		tsi: 'Tsimshian',
		tsn: 'Tswana',
		tso: 'Tsonga',
		tuk: 'Turkmen',
		tum: 'Tumbuka',
		tur: 'Turkish',
		tvl: 'Tuvalua',
		twi: 'Twi',
		tyv: 'Tuvinian',
		udm: 'Udmurt',
		uig: 'Uighur',
		ukr: 'Ukrainian',
		umb: 'Umbundu',
		urd: 'Urdu',
		uzb: 'Uzbek',
		vai: 'Vai',
		ven: 'Venda',
		vie: 'Vietnamese',
		vot: 'Votic',
		wal: 'Wolaitta',
		war: 'Waray',
		was: 'Washo',
		wln: 'Walloon',
		wol: 'Wolof',
		xal: 'Kalmyk',
		xho: 'Xhosa',
		yao: 'Yao',
		yap: 'Yapese',
		yid: 'Yiddish',
		yor: 'Yoruba',
		zap: 'Zapotec',
		zen: 'Zenaga',
		zgh: 'Standard Moroccan Tamazight',
		zha: 'Zhuang',
		zul: 'Zulu',
		zun: 'Zuni',
		zza: 'Zaza'
	},
	other: {
		akk: 'Akkadian',
		arc: 'Official Aramaic',
		ave: 'Avestan',
		chu: 'Church Slavic',
		egy: 'Egyptian',
		elx: 'Elamite',
		gez: 'Geez',
		got: 'Gothic',
		hit: 'Hittite',
		kaw: 'Kawi',
		kho: 'Khotanese',
		lat: 'Latin',
		pal: 'Pahlavi',
		phn: 'Phoenician',
		pli: 'Pali',
		san: 'Sanskrit',
		sog: 'Sogdian',
		sux: 'Sumerian',
		uga: 'Ugaritic',
		afa: 'Afro-Asiatic languages',
		alg: 'Algonquian languages',
		apa: 'Apache languages',
		art: 'Artificial languages',
		ath: 'Athapascan languages',
		aus: 'Australian languages',
		bad: 'Banda languages',
		bai: 'Bamileke languages',
		bat: 'Baltic languages',
		ber: 'Berber languages',
		bih: 'Bihari languages',
		bnt: 'Bantu languages',
		btk: 'Batak languages',
		cai: 'Central American Indian languages',
		cau: 'Caucasian languages',
		cel: 'Celtic languages',
		cmc: 'Chamic languages',
		cpe: 'English based Creoles and pidgins',
		cpf: 'French-based Creoles and pidgins',
		cpp: 'Portuguese-based Creoles and pidgins',
		crp: 'Creoles and pidgins',
		cus: 'Cushitic languages',
		day: 'Land Dayak languages',
		dra: 'Dravidian languages',
		fiu: 'Finno-Ugrian languages',
		gem: 'Germanic languages',
		him: 'Himachali languages',
		ijo: 'Ijo languages',
		inc: 'Indic languages',
		ine: 'Indo-European languages',
		ira: 'Iranian languages',
		iro: 'Iroquoian languages',
		kar: 'Karen languages',
		khi: 'Khoisan languages',
		kro: 'Kru languages',
		map: 'Austronesian languages',
		mis: 'Uncoded languages',
		mkh: 'Mon-Khmer languages',
		mno: 'Manobo languages',
		mul: 'Multiple languages',
		mun: 'Munda languages',
		myn: 'Mayan languages',
		nah: 'Nahuatl languages',
		nai: 'North American Indian languages',
		nic: 'Niger-Kordofanian languages',
		nub: 'Nubian languages',
		oto: 'Otomian languages',
		paa: 'Papuan languages',
		phi: 'Philippine languages',
		pra: 'Prakrit languages',
		roa: 'Romance languages',
		sai: 'South American Indian languages',
		sal: 'Salishan languages',
		sem: 'Semitic languages',
		sgn: 'Sign languages',
		sio: 'Siouan languages',
		sit: 'Sino-Tibetan languages',
		sla: 'Slavic languages',
		smi: 'Sami languages',
		son: 'Songhai languages',
		ssa: 'Nilo-Saharan languages',
		tai: 'Tai languages',
		tup: 'Tupi languages',
		tut: 'Altaic languages',
		und: 'Undetermined',
		wak: 'Wakashan languages',
		wen: 'Sorbian languages',
		ypk: 'Yupik languages',
		znd: 'Zande languages',
		zxx: 'No linguistic content'
	}
};


export const MAPPING_ISO_2_FLAT = () => {
	const o: Record<string, string> = {};
	for (const x of Object.values(MAPPING_ISO_639_2)) {
		Object.assign(o, x);
	}
	return o;
}
